### ISSUE TITLE
Support light mode

### ISSUE THREAD

**Issue by u0nel** [nathanielfernandes/lingo#3]
![image](https://user-images.githubusercontent.com/46542757/156891545-c226dc0d-dbf1-43be-ba59-aed0ba194d43.png)
This is extremely hard to read.

**Comment by nathanielfernandes** [comment]
i didn't think about this, i'll add dynamic colors for both light and dark backgrounds

**Comment by nathanielfernandes** [comment]
The text will now adjust for light or dark backgrounds
![](https://cdn.discordapp.com/attachments/792686378366009354/949753681153232916/unknown.png)
![](https://cdn.discordapp.com/attachments/792686378366009354/949754212487659570/unknown.png)
